"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const swagger_1 = __importDefault(require("../common/swagger"));
const admin_config_1 = __importDefault(require("./admin-config"));
const application_1 = __importDefault(require("./application"));
const catalogue_1 = __importDefault(require("./catalogue"));
const document_1 = __importDefault(require("./document"));
const employee_1 = __importDefault(require("./employee"));
const fee_details_1 = __importDefault(require("./fee-details"));
const institute_1 = __importDefault(require("./institute"));
const instituteworkinghours_1 = __importDefault(require("./instituteworkinghours"));
const leave_form_1 = __importDefault(require("./leave-form"));
const metadatacontent_1 = __importDefault(require("./metadatacontent"));
const metadatafeeconcession_1 = __importDefault(require("./metadatafeeconcession"));
const metadataschema_1 = __importDefault(require("./metadataschema"));
const metadatastaticcollection_1 = __importDefault(require("./metadatastaticcollection"));
const payment_integration_1 = __importDefault(require("./payment-integration"));
const role_management_1 = __importDefault(require("./role-management"));
const student_1 = __importDefault(require("./student"));
const timetable_1 = __importDefault(require("./timetable"));
const user_1 = __importDefault(require("./user"));
const router = new express_1.Router();
router.use("/users", user_1.default);
router.use("/api-docs", swagger_1.default);
router.use("/metadatacontents", metadatacontent_1.default);
router.use("/catalogues", catalogue_1.default);
router.use("/metadatastaticcollections", metadatastaticcollection_1.default);
router.use("/metadataschemas", metadataschema_1.default);
router.use("/metadatafeeconcessions", metadatafeeconcession_1.default);
router.use("/applications", application_1.default);
router.use("/payment-integrations", payment_integration_1.default);
router.use("/admin-configs", admin_config_1.default);
router.use("/documents", document_1.default);
router.use("/students", student_1.default);
router.use("/employees", employee_1.default);
router.use("/institutes", institute_1.default);
router.use("/instituteworkinghours", instituteworkinghours_1.default);
router.use("/fees", fee_details_1.default);
router.use("/roles", role_management_1.default);
router.use("/leave-form", leave_form_1.default);
router.use("/timetable", timetable_1.default);
exports.default = router;
