"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const config_1 = require("../../config");
const path = require("path");
const router = new express_1.Router();
const swaggerUi = require("swagger-ui-express");
const YAML = require("yamljs");
const yamlPath = path.join(__dirname, "/swagger.yaml");
const swaggerDocument = YAML.load(yamlPath);
swaggerDocument.host = config_1.SWAGGER_API_HOST;
router.use("/", swaggerUi.serve, swaggerUi.setup(swaggerDocument));
exports.default = router;
